module.exports = {
  URL: {
    BASE_URL: 'https://api.themoviedb.org/3/',
    IMAGE_URL: 'https://image.tmdb.org/t/p/w500/',
    API_KEY: 'api_key=9730498eaa14410d780907df75257b76',
    API_ACCESS_TOKEN:
      'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5NzMwNDk4ZWFhMTQ0MTBkNzgwOTA3ZGY3NTI1N2I3NiIsInN1YiI6IjVlZjA4MTk1NTY4NDYzMDAzMzAyYTZhMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.UiUaqElCbZo5JwmCmsWgumF4ymNKJvGGrC-eSNS5BiI',
    REQUEST_TOKEN_URL: 'authentication/token/new',
    VALIDATE_WITH_LOGIN_URL: 'authentication/token/validate_with_login',
    CREATE_SESSION_URL: 'authentication/session/new',
    ACCOUNT_URL:'account',
  },
  Strings: {
    USER_NAME: 'amitd',
    PASSWORD: '1qaz@WSX',
    MAIN_TITLE: 'Movies',
    SEARCH_BUTTON: 'Search',
    SECONDARY_TITLE: 'Movie Details',
    INVALID_INPUT: 'Invalid input.',
    SEARCH_TTITLE: 'Search movie and modify favorite property',
    PLACEHOLDER: 'Enter search text',
    MOVIES_LIST_BUTTON: 'Popular movies list',
    NEXT_PAGE: 'Next',
    BACK_PAGE: 'Back',
    FAVORIATE_LIST_BUTTON: 'Favoriate movies list',
    RELEASE_DATE: 'Relase Date: ',
    NO_FAVORIATE_MOVIES: 'No favoriate movies.',
    NO_DATA_FOUND: 'No data found.',
    LANGUAGE: 'Language: ',
    POPULARITY: 'Popularity: ',
    STATUS: 'Status: ',
    RATINGS: 'Ratings: ',
    BUDGET: 'Budget: ',
    REVENUE: 'Revenue: ',
    RUNTIME: 'Runtime: ',
    OVERVIEW: 'Overview: ',
    MSG: 'This field is required.',
    FAVORITE: 'Favorite',
  },
  Colors: {
    Cyan: '#02ADAD',
    Grey: '#EDEDED',
    black: 'black',
    Transparent: 'transparent',
    White: '#fff',
  },
};
